# Generated by Django 2.2.4 on 2019-08-21 01:54

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_role', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('threads', models.PositiveIntegerField(default=0)),
                ('posts', models.PositiveIntegerField(default=0)),
                ('last_post_on', models.DateTimeField(blank=True, null=True)),
                ('last_thread_title', models.CharField(blank=True, max_length=255, null=True)),
                ('last_thread_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('last_poster_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_poster_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('require_threads_approval', models.BooleanField(default=False)),
                ('require_replies_approval', models.BooleanField(default=False)),
                ('require_edits_approval', models.BooleanField(default=False)),
                ('prune_started_after', models.PositiveIntegerField(default=0)),
                ('prune_replied_after', models.PositiveIntegerField(default=0)),
                ('css_class', models.CharField(blank=True, max_length=255, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
