# Generated by Django 2.2.4 on 2019-08-21 09:54

from django.db import migrations, models
import misago.users.avatars.store


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=30)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('email_hash', models.CharField(max_length=32)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('requires_activation', models.PositiveIntegerField(default=0)),
                ('acl_key', models.CharField(blank=True, max_length=12, null=True)),
                ('is_active_staff_message', models.TextField(blank=True, null=True)),
                ('is_deleting_account', models.BooleanField(default=False)),
                ('avatar_crop', models.CharField(blank=True, max_length=255, null=True)),
                ('is_avatar_locked', models.BooleanField(default=False)),
                ('avatar_lock_user_message', models.TextField(blank=True, null=True)),
                ('avatar_lock_staff_message', models.TextField(blank=True, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('signature_parsed', models.TextField(blank=True, null=True)),
                ('signature_checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('is_signature_locked', models.BooleanField(default=False)),
                ('signature_lock_user_message', models.TextField(blank=True, null=True)),
                ('signature_lock_staff_message', models.TextField(blank=True, null=True)),
                ('followers', models.PositiveIntegerField(default=0)),
                ('following', models.PositiveIntegerField(default=0)),
                ('unread_private_threads', models.PositiveIntegerField(default=0)),
                ('sync_unread_private_threads', models.BooleanField(default=False)),
                ('threads', models.PositiveIntegerField(default=0)),
                ('posts', models.PositiveIntegerField(db_index=True, default=0)),
                ('last_posted_on', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into admin sites.', verbose_name='staff status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(max_length=255, upload_to=misago.users.avatars.store.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('css_class', models.CharField(blank=True, max_length=255, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_tab', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
