# Generated by Django 2.2.4 on 2019-08-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misago_users', '0002_auto_20190819_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
