# Generated by Django 2.2.4 on 2019-08-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misago_users', '0004_auto_20190819_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_hash',
            field=models.CharField(max_length=32),
        ),
    ]
