# Generated by Django 2.2.4 on 2019-08-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misago_users', '0005_auto_20190819_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into admin sites.', verbose_name='staff status'),
        ),
    ]
