# Generated by Django 2.2.4 on 2019-08-20 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misago_users', '0006_user_is_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
