# Generated by Django 2.2.4 on 2019-08-20 07:50

from django.db import migrations, models
import misago.cache.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheVersion',
            fields=[
                ('cache', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('version', models.CharField(default=misago.cache.utils.generate_version_string, max_length=8)),
            ],
        ),
    ]
